### ISSUE TITLE
Use a design pattern and make necessary changes to the about page

### ISSUE THREAD

**Issue by rithiksachdev** [rithiksachdev/ecellweb#21]
You can use the box-shadow, parallax effect and more to make it look better. (Evoke Enterprise Expand should come after about us.)

**Comment by divyanshsood00** [comment]
looks better now.
Subtle improvements in about us.
Added mentor cards' details and yet to configure the time updated.

**Comment by divyanshsood00** [comment]
evoke enterprise and expand cards' colour scheme changed .... yet far from perfect

**Comment by Git-Harshit** [comment]
The time elapsed since modification statement "Last Updated on ..." could be removed for now. 

Be aware that @priyanshi-2508 is also working on about page, and should commit her changes in some time. Make sure that your changes don't clash with her updates. You can discuss it with her what she's working on.
